    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        steps:
          # Adapted from android-actions/setup-android
          - name: JDK Setup
            uses: actions/setup-java@v1
            with:
              java-version: 1.11

          - name: Checkout
            uses: actions/checkout@v2

          - name: Setup Android SDK
            uses: android-actions/setup-android@v2

          - name: Build JChef
            run: ./gradlew --no-daemon build

          - name: Testing
            uses: education/autograding@v1
